theme: jekyll-theme-cayman
title: Shivam Vats
description: Data Science Graduate Student at CU Boulder
show_downloads: true
github:
  linkedin_url: https://www.linkedin.com/in/vats-shivam/
  Github_url: https://github.com/shivam360d
  resume_url: https://raw.githubusercontent.com/shivam360d/ShivamVats/main/Shivam_Vats_Resume.pdf
